#!/bin/sh
chmod +x elfreaderb
for a in `ls elfs`; do
  echo $a >> b.txt
  echo ==================== >> b.txt
  readelf -a ./elfs/$a | grep -n -A 10 '.rel.text' >> b.txt
  echo ==================== >> b.txt
done
